### ISSUE TITLE
Other projects? Lay of the land?

### ISSUE THREAD

**Issue by tony** [williamcotton/search-input-query#1]
Hi, thank you for the project!

I came across your project looking to get a friendly way to do lucene-style queries in input boxes (and also provide at AST of query itself).

Are their similar projects out there you've found that are actually active? Planning on continuing yours?

# Parsing

- search-input-query-parser _(here)_: [npm](https://www.npmjs.com/package/search-input-query-parser), [repo](https://github.com/williamcotton/search-input-query)
- lucene-kit: [npm](https://github.com/oxdev03/lucene-kit), [repo](https://www.npmjs.com/package/lucene-kit)
- The underlying parsing projects that rely on PEG grammars are in bad shape. Lots of abandoned projects, or they don't work with TypeScript, or ESM.

# Searching

- search-input-query-react _(here)_: [npm](https://www.npmjs.com/package/search-input-query-react), [repo](https://github.com/williamcotton/search-input-query/tree/main/search-input-query-react)
- react-structured-search: [npm](https://www.npmjs.com/package/react-structured-search), [repo](https://github.com/quang1225/react-structured-search)

P.S. You Look prodigy level at TypeScript search parsing and inputs. I see https://github.com/williamcotton/guish also.

**Comment by williamcotton** [comment]
Hey @tony - I'm glad you stumbled across this repo and find it useful!

Thanks for the high-level view of other related projects, I'm definitely interested in seeing some other approaches. Your research has probably led you to know more about the landscape than I do!

Yes, I am planning on continuing development, and the impetus is that we're actively using this parser and React component at my workplace.

I'd say at this point in the development process that this should be considered alpha software. I plan on doing a launch on HackerNews at some point after the holiday season.

I hope you're doing well and think you for the kind words!
